# Site wide configuration

title: AKdev
locale: pt_BR
timezone: America/Sao_Paulo
description: Aventuras e desaventuras no desenvolvimento.
#logo: site-logo.png
search: true
url: http://adirkuhn.github.io
paginate: 10
paginate_path: "/pagina/:num"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Adir Kuhn
  avatar: ak.jpeg
  email: adirkuhn@gmail.com
  disqus-shortname:
  twitter: adirkuhn
  facebook: #username
  github: adirkuhn
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: adirkuhn
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-41280748-3
    verify:
    ad-client:
    ad-slot: 
  bing-verify: